#!/usr/bin/env python3
"""Measure the dataset and write the result into README.md.

    python3 tools/build_stats.py

The figures are generated and not typed, so the README cannot drift from the
data. Everything the browse page needs to offer as a partition, a scale or a
filter is measured here first.

The output replaces whatever sits between the two markers in README.md; the
rest of the file is hand-written and is left alone. There used to be a separate
ESTADISTICAS.md, which nobody read because *.md is excluded from the deploy and
the README is the document a newcomer opens.

2026 Alejandro Rojo Gualix - MIT
"""

import json
import os
import re
from collections import Counter, defaultdict

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(ROOT, 'data', 'derivedmergeddata.js')
OUT = os.path.join(ROOT, 'README.md')
BEGIN = '<!-- BEGIN STATS -->'
END = '<!-- END STATS -->'

IDS = set('⿰⿱⿲⿳⿴⿵⿶⿷⿸⿹⿺⿻')
IDS_NAME = {
    '⿰': 'left · right', '⿱': 'top · bottom',
    '⿲': 'three in a row', '⿳': 'three stacked',
    '⿴': 'fully surrounds', '⿵': 'surrounds from above', '⿶': 'surrounds from below',
    '⿷': 'surrounds from the left', '⿸': 'surrounds top-left',
    '⿹': 'surrounds top-right', '⿺': 'surrounds bottom-left',
    '⿻': 'overlaid',
}


def load():
    with open(DATA, encoding='utf-8') as f:
        s = f.read()
    return json.loads(s[s.index('{'):].rstrip().rstrip(';'))


L = load()
N = len(L)


def pct(n, of=None):
    return '%.1f %%' % (100.0 * n / (of or N))


# ── The three ways a grapheme comes apart ────────────────────────────────────
# They are different measures over different sources, and they disagree on
# purpose. Saying "divisibility" without saying which one is how the workshop
# note and this script ended up reporting 7 and 8 for the same character.

def kids_etymological(c):
    e = (L.get(c) or {}).get('etymology') or {}
    return [e[k] for k in ('semantic', 'phonetic') if e.get(k)]


def kids_ids(c):
    d = (L.get(c) or {}).get('decomposition', '')
    if not d or d == '？':
        return []
    return [x for x in d if x not in IDS and x != '？' and x != c]


def kids_wikimedia(c):
    g = (L.get(c) or {}).get('graphicaldecomposition') or {}
    return [g[k] for k in ('LeftComponent', 'RightComponent') if g.get(k) and g[k] != c]


def depth(c, kids, seen=frozenset()):
    """Levels of nesting: a grapheme that does not come apart is 0. Cycles
    guarded — 舉 contains itself and made the original code recurse forever."""
    if c in seen or c not in L:
        return 0
    return 1 + max([depth(x, kids, seen | {c}) for x in kids(c)] + [0])


def depth_table(kids):
    d = {c: depth(c, kids) - 1 for c in L}
    return d, Counter(d.values())


def strokes(c):
    return len((L.get(c) or {}).get('matches') or [])


def series(c):
    g = ((L.get(c) or {}).get('BaxterSagart') or {}).get('GSR') or ''
    m = re.match(r'\d+', g)
    return m.group() if m else None


def build():
    o = []
    w = o.append

    w('<!-- BEGIN STATS -->')
    w('<!-- Generated by tools/build_stats.py. Do not edit between the markers. -->')
    w('## The dataset, measured\n')
    w('Every figure below is recomputed from `data/derivedmergeddata.js` by')
    w('`tools/build_stats.py`, so it cannot drift from the data. This is both the')
    w('inventory of what the browse page can offer as a partition, a scale or a')
    w('filter, and the record of what has been measured, so as not to measure it')
    w('twice.\n')
    w('**%d entries in all.**\n' % N)

    # -- Coverage -------------------------------------------------------------
    w('### 1. What an entry carries\n')
    w('Before counting anything, how much data there is. A column with 35 % coverage')
    w('cannot be offered the same way as one with 100 %.\n')
    w('| Field | Entries | Coverage |')
    w('|---|---:|---:|')
    fields = [
        ('`radical`', sum(1 for v in L.values() if v.get('radical'))),
        ('`pinyin`', sum(1 for v in L.values() if v.get('pinyin'))),
        ('`decomposition`', sum(1 for v in L.values() if v.get('decomposition'))),
        ('`definition`', sum(1 for v in L.values() if v.get('definition'))),
        ('`etymology.hint`', sum(1 for v in L.values() if (v.get('etymology') or {}).get('hint'))),
        ('`graphicaldecomposition`', sum(1 for v in L.values() if v.get('graphicaldecomposition'))),
        ('`etymology`', sum(1 for v in L.values() if v.get('etymology'))),
        ('`etymology.semantic`', sum(1 for v in L.values() if (v.get('etymology') or {}).get('semantic'))),
        ('`etymology.phonetic`', sum(1 for v in L.values() if (v.get('etymology') or {}).get('phonetic'))),
        ('`BaxterSagart`', sum(1 for v in L.values() if v.get('BaxterSagart'))),
    ]
    for name, n in fields:
        w('| %s | %d | %s |' % (name, n, pct(n)))
    w('')
    hint = sum(1 for v in L.values() if (v.get('etymology') or {}).get('hint'))
    w('**`hint` is the most didactic field and the least used**: it covers %s and is'
      % pct(hint))
    w('plain prose explaining the composition — \u2e8a "A crack on an oracle bone",')
    w('\u707e "A house \u5b80 on fire \u706b".\n')

    # -- Origin ---------------------------------------------------------------
    w('### 2. Origin: how pictograms, ideograms and phonosemantograms are told apart\n')
    w('It is not interpretation: it is the **`etymology.type`** field, which comes')
    w('from makemeahanzi (Unihan + CJKlib).\n')
    w('| Class | Entries | Of the total | Of those with an etymology |')
    w('|---|---:|---:|---:|')
    types = Counter((v.get('etymology') or {}).get('type') for v in L.values())
    with_ety = sum(n for t, n in types.items() if t)
    for t, n in types.most_common():
        if t is None:
            continue
        w('| `%s` | %d | %s | %s |' % (t, n, pct(n), pct(n, with_ety)))
    w('| *no etymology* | %d | %s | \u2014 |' % (types[None], pct(types[None])))
    w('')
    w('It is a **partition** — each entry falls in one class and only one — but over')
    w('the **%d that have an etymology, not over the %d**. The other %d say nothing.\n'
      % (with_ety, N, types[None]))
    ps = [v for v in L.values() if (v.get('etymology') or {}).get('type') == 'pictophonetic']
    both = sum(1 for v in ps if v['etymology'].get('phonetic') and v['etymology'].get('semantic'))
    no_p = sum(1 for v in ps if not v['etymology'].get('phonetic'))
    no_s = sum(1 for v in ps if not v['etymology'].get('semantic'))
    w('And the largest class is not homogeneous. Of the %d phonosemantograms, **%d'
      % (len(ps), both))
    w('declare both parts**; %d do not say which is the phonetic one and %d do not say'
      % (no_p, no_s))
    w('which is the semantic one. Filtering by "phonosemantogram" therefore returns %d'
      % len(ps))
    w('entries of which %d cannot be taken apart.\n' % (len(ps) - both))

    # -- Divisibility ---------------------------------------------------------
    w('### 3. Divisibility: there are **three** measures, not one\n')
    w('This is the easiest place to go wrong, and it happened: a workshop note said 7')
    w('and a later measurement said 8 **for the same character**. They do not')
    w('contradict each other; they measure different things over different sources.\n')
    w('The convention, here and in the article: **a grapheme that does not come apart')
    w('is 0**.\n')
    de, ce = depth_table(kids_etymological)
    di, ci = depth_table(kids_ids)
    dw, cw = depth_table(kids_wikimedia)
    levels = sorted(set(ce) | set(ci) | set(cw))
    w('| Level | Etymological | Graphic IDS | Graphic Wikimedia |')
    w('|---:|---:|---:|---:|')
    for k in levels:
        w('| %d | %s | %s | %s |' % (k,
                                     ce.get(k, '\u2014') or '\u2014',
                                     ci.get(k, '\u2014') or '\u2014',
                                     cw.get(k, '\u2014') or '\u2014'))
    w('')
    for name, d, source in (
            ('Etymological', de, '`etymology.semantic` + `etymology.phonetic`, recursive'),
            ('Graphic IDS', di, '`decomposition`, the n-ary \u2ff0\u2ff1\u2ff2\u2026 tree'),
            ('Graphic Wikimedia', dw, '`graphicaldecomposition`, binary left/right')):
        mx = max(d.values())
        top = sorted(c for c, v in d.items() if v == mx)
        w('- **%s** \u2014 %s.' % (name, source))
        w('  Tops out at **%d**, reached by **%d**: %s' % (mx, len(top), ' '.join(top)))
    w('')
    w('The etymological one is the article\'s: **4, and only \u790c \u81df \u8619 \u87ee**. The Wikimedia')
    w('one is that of `0OFFLINE/mi an\u00e1lisis/ConclusionsGraphic2Recursivity.md`: **7, and')
    w('only \u64f2 \u8e51**, which is why \u8e51 is the character `analysis.html` opens with.\n')

    # -- Radical vs semantic component ----------------------------------------
    w('### 4. Radical against semantic component\n')
    w('The radical is the dictionary\'s postal address; the semantic component is an')
    w('etymological fact. They almost always agree, and where they do not is where')
    w('convention parts from history.\n')
    con = [(k, v) for k, v in L.items() if (v.get('etymology') or {}).get('semantic')]
    ig = sum(1 for k, v in con if v.get('radical') == v['etymology']['semantic'])
    w('| | Entries |')
    w('|---|---:|')
    w('| With a declared semantic component | %d |' % len(con))
    w('| The radical **is** the semantic component | %d (%s) |' % (ig, pct(ig, len(con))))
    w('| The radical is **something else** | %d (%s) |' % (len(con) - ig, pct(len(con) - ig, len(con))))
    w('')
    rads = {v['radical'] for v in L.values() if v.get('radical')}
    sems = {v['etymology']['semantic'] for _, v in con}
    w('And as sets they **overlap; neither contains the other**:\n')
    w('| | How many |')
    w('|---|---:|')
    w('| In both roles | %d |' % len(rads & sems))
    w('| Radical only | %d |' % len(rads - sems))
    w('| Semantic component only | %d |' % len(sems - rads))
    w('')
    w('Examples where they diverge:\n')
    w('| Grapheme | Radical | Semantic | Meaning |')
    w('|---|---|---|---|')
    n = 0
    for k, v in con:
        if v.get('radical') != v['etymology']['semantic']:
            w('| %s | %s | %s | %s |' % (k, v['radical'], v['etymology']['semantic'],
                                         (v.get('definition') or '')[:40]))
            n += 1
            if n >= 6:
                break
    w('')

    # -- Layout ---------------------------------------------------------------
    w('### 5. Layout in the square\n')
    w('The top-level IDS operator. It is the second true partition.\n')
    w('| Operator | What it says | Entries | |')
    w('|---|---|---:|---:|')
    c = Counter((v.get('decomposition') or '\uff1f')[0] for v in L.values())
    for k, n in c.most_common():
        if k in IDS_NAME:
            w('| %s | %s | %d | %s |' % (k, IDS_NAME[k], n, pct(n)))
    other = sum(n for k, n in c.items() if k not in IDS_NAME)
    w('| \uff1f and others | not decomposed | %d | %s |' % (other, pct(other)))
    w('')
    odd = [(k, v['decomposition']) for k, v in L.items()
           if (v.get('decomposition') or '')[:1] and v['decomposition'][0] not in IDS
           and v['decomposition'] != '\uff1f']
    if odd:
        w('%d entries have a decomposition with no operator, and they are not' % len(odd))
        w('malformed: they are **derivation by stroke modification**, a relation the IDS')
        w('format has no way to name.\n')
        w('| Grapheme | Derives from | Meaning |')
        w('|---|---|---|')
        for k, d in odd:
            w('| %s | %s | %s |' % (k, d, (L[k].get('definition') or '')[:40]))
        w('')

    # -- Order ----------------------------------------------------------------
    w('### 6. Order of the parts\n')
    c = Counter((v.get('etymology') or {}).get('order', '(not stated)') for v in L.values()
                if (v.get('etymology') or {}).get('type') == 'pictophonetic')
    w('| Order | Entries |')
    w('|---|---:|')
    for k, n in c.most_common():
        w('| `%s` | %d |' % (k, n))
    w('')

    # -- Attestation ----------------------------------------------------------
    w('### 7. How far back the evidence goes\n')
    w('Which stage of the language backs each grapheme. It matters because **a')
    w('phonetic branch only sounds alike in Old Chinese**: in modern Mandarin \u5404 g\u00e8,')
    w('\u683c g\u00e9 and \u843d lu\u00f2 look like no family at all, and in Old Chinese `*k\u02e4ak`,')
    w('`*k\u02e4rak` and `*k\u0259.r\u02e4ak` are one beyond argument.\n')
    oc = sum(1 for v in L.values() if ((v.get('BaxterSagart') or {}).get('OC') or '').strip())
    mc = sum(1 for v in L.values() if ((v.get('BaxterSagart') or {}).get('MC') or '').strip()
             and not ((v.get('BaxterSagart') or {}).get('OC') or '').strip())
    py = sum(1 for v in L.values() if not v.get('BaxterSagart') and v.get('pinyin'))
    w('| Stage | Entries | |')
    w('|---|---:|---:|')
    w('| Old Chinese (Baxter-Sagart) | %d | %s |' % (oc, pct(oc)))
    w('| Middle Chinese only | %d | %s |' % (mc, pct(mc)))
    w('| Modern pinyin only | %d | %s |' % (py, pct(py)))
    w('| Nothing | %d | %s |' % (N - oc - mc - py, pct(N - oc - mc - py)))
    w('')
    w('**There is not one case of Middle Chinese without Old Chinese**: in practice the')
    w('scale is binary, attested or not. And the "pinyin only" bucket is where the')
    w('20th-century coinages land \u2014 \u6c2b ammonia, \u70f4 hydrocarbon, \u783c concrete \u2014 which use')
    w('the same procedure two thousand years later. **The data cannot say "coinage"**,')
    w('only "unattested in the classical corpus".\n')

    # -- Role in the system ---------------------------------------------------
    w('### 8. What each grapheme does with the others\n')
    fon, sem = defaultdict(list), defaultdict(list)
    for k, v in L.items():
        e = v.get('etymology') or {}
        if e.get('phonetic'):
            fon[e['phonetic']].append(k)
        if e.get('semantic'):
            sem[e['semantic']].append(k)
    used = set(fon) | set(sem)
    w('| Role | How many |')
    w('|---|---:|')
    w('| Serves as a **phonetic** component to others | %d |' % len(fon))
    w('| Serves as a **semantic** component to others | %d |' % len(sem))
    w('| Does both | %d |' % len(set(fon) & set(sem)))
    w('| Phonetic only | %d |' % len(set(fon) - set(sem)))
    w('| Semantic only | %d |' % len(set(sem) - set(fon)))
    w('| **Composes nothing** (a leaf of the system) | %d (%s) |'
      % (N - len(used), pct(N - len(used))))
    w('')
    w('**%s of graphemes compose nothing.** The system has a small set of parts'
      % pct(N - len(used)))
    w('\u2014 %d phonetic and %d semantic \u2014 and a very long tail of leaves. And the two'
      % (len(fon), len(sem)))
    w('kinds are not evenly shared: **%d phonetic components against %d semantic**,'
      % (len(fon), len(sem)))
    w('which is the asymmetry underneath the whole system.\n')
    deep_sem = {r: depth(r, lambda c: sem.get(c, [])) for r in sem}
    deep = [r for r, d in deep_sem.items() if d >= 3]
    w('From which it follows that **the semantic relation is not a tree but a')
    w('classification**: only **%d** of the %d semantic components have any depth;'
      % (len(deep), len(sem)))
    w('\u6c35 has %d children and no grandchildren. The phonetic one really is a'
      % len(sem.get('\u6c35', [])))
    w('genealogy.\n')
    top_f = sorted(fon.items(), key=lambda kv: -len(kv[1]))[:5]
    top_s = sorted(sem.items(), key=lambda kv: -len(kv[1]))[:5]
    w('| Most prolific | |')
    w('|---|---|')
    w('| Phonetic | %s |' % ' \u00b7 '.join('%s (%d)' % (k, len(v)) for k, v in top_f))
    w('| Semantic | %s |' % ' \u00b7 '.join('%s (%d)' % (k, len(v)) for k, v in top_s))
    w('')

    # -- Strokes --------------------------------------------------------------
    w('### 9. Strokes\n')
    t = sorted(strokes(c) for c in L)
    w('**`len(matches)` is the stroke count.** It is documented nowhere and was')
    w('deduced: checked against 13 control characters \u2014 \u9fa0 = 17 \u2713, \u9f8d = 16 \u2713 \u2014 and')
    w('then against Baxter-Sagart over 265 variant pairs, where **261 agree** that the')
    w('attested member is the one with more strokes.\n')
    w('Range **%d to %d**, median **%d**.\n' % (t[0], t[-1], t[len(t) // 2]))

    # -- Karlgren -------------------------------------------------------------
    w('### 10. Agreement with Karlgren\n')
    w('The `BaxterSagart.GSR` field is Karlgren\'s phonetic series number, and it works')
    w('as an **independent check on every phonetic edge**: if two related graphemes')
    w('fall in the same series, the relation is confirmed by a source other than the')
    w('one that asserted it.\n')
    ok = bad = na = 0
    for k, v in L.items():
        ph = (v.get('etymology') or {}).get('phonetic')
        if not ph:
            continue
        a, b = series(k), series(ph)
        if not a or not b:
            na += 1
        elif a == b:
            ok += 1
        else:
            bad += 1
    w('| | Edges |')
    w('|---|---:|')
    w('| Same series: the relation is confirmed | %d (%s) |' % (ok, pct(ok, ok + bad)))
    w('| Different series: the relation is disputed | %d (%s) |' % (bad, pct(bad, ok + bad)))
    w('| No data at one end | %d |' % na)
    w('')
    w('That %s that disagrees is not noise in the way: it is where a reader learns'
      % pct(bad, ok + bad))
    w('that this is reconstruction and not dogma, which is why it is marked rather')
    w('than hidden.\n')

    # -- Variants -------------------------------------------------------------
    w('### 11. Traditional and simplified\n')
    w('**The data has no field for this.** They are detected as siblings under the')
    w('same phonetic component that share pinyin **and** definition. Within the pair,')
    w('the one in Baxter-Sagart is the traditional form; if neither is, the one with')
    w('more strokes.\n')
    groups = []
    for root, kids in fon.items():
        b = defaultdict(list)
        for c in kids:
            v = L[c]
            if v.get('pinyin') and v.get('definition'):
                b[(tuple(v['pinyin']), v['definition'].strip())].append(c)
        groups += [g for g in b.values() if len(g) > 1]
    has = lambda c: bool((L.get(c) or {}).get('BaxterSagart'))
    one = sum(1 for g in groups if sum(map(has, g)) == 1)
    w('| | How many |')
    w('|---|---:|')
    w('| Variant groups detected | %d |' % len(groups))
    w('| Graphemes involved | %d |' % sum(len(g) for g in groups))
    w('| Decidable by Baxter-Sagart | %d |' % one)
    w('| Decided by stroke count | %d |' % (len(groups) - one))
    w('')
    w('**Only pairs that are siblings are visible.** A pair split across two different')
    w('branches is never matched, and there is no telling how many those are. With')
    w('Unihan\'s `kSimplifiedVariant` this would be exact instead of heuristic.\n')

    # What the merge costs, because two numbers in one project that disagree
    # without saying why are worse than either of them alone. The trees count
    # WORDS (a pair is one node with two spellings); everything above this line
    # counts GLYPHS. These are the same measurements taken the other way.
    canon = {}
    for g in groups:
        t = [c for c in g if has(c)]
        head = t[0] if len(t) == 1 else sorted(g, key=lambda c: -strokes(c))[0]
        for c in g:
            canon[c] = head

    def merged(kids):
        node = lambda c: canon.get(c, c)
        nodes = set(node(c) for c in kids)
        def ch(n):
            ms = [n] + [c for c, h in canon.items() if h == n and c != n]
            out = set()
            for m in ms:
                for c in kids.get(m, []):
                    if node(c) != n:
                        out.add(node(c))
            return out
        def d(n, seen):
            if n in seen:
                return 0
            seen = seen | {n}
            return 1 + max([d(x, seen) for x in ch(n)] + [0])
        return nodes, ch, d

    pn, pch, pd = merged(fon)
    sn, sch, sd = merged(sem)
    deep_glyphs = len(deep)
    deep_nodes = sum(1 for r in sn if sd(r, frozenset()) >= 3)
    w('**Counting words instead of glyphs changes the totals**, which is what the')
    w('composition trees do: there a pair is one node with two spellings, not two')
    w('siblings that happen to mean the same.\n')
    w('| | Glyphs | Words |')
    w('|---|---:|---:|')
    w('| Phonetic components | %d | %d |' % (len(fon), len(pn)))
    w('| Semantic components | %d | %d |' % (len(sem), len(sn)))
    w('| Semantic components with depth | %d | %d |' % (deep_glyphs, deep_nodes))
    w('| Children of \u6c35 | %d | %d |' % (len(sem.get('\u6c35', [])), len(sch('\u6c35'))))
    w('')
    w('⭐ **The merge does not only subtract: it creates one level of depth.** A')
    w('semantic component whose two spellings each composed a different grapheme')
    w('was two flat entries and becomes one node with a generation under it, which')
    w('is why the trees offer %d semantic roots and this page counts %d.\n'
      % (deep_nodes, deep_glyphs))

    # -- Close ----------------------------------------------------------------
    w('### 12. What is a partition and what is a facet\n')
    w('This is what decides the design of the browse page. Mixing them into a single')
    w('menu would misrepresent the data.\n')
    w('| Kind | Which |')
    w('|---|---|')
    w('| **Partitions** (one selector, exclusive) | Origin \u00b7 Layout |')
    w('| **Scales** (a range) | Etymological divisibility \u00b7 IDS \u00b7 Wikimedia \u00b7 Strokes |')
    w('| **Filters** (a checkbox) | Attested in Old Chinese \u00b7 Radical \u2260 semantic \u00b7 Composes others \u00b7 Karlgren disagrees \u00b7 Is a variant |')
    w('| **Enumeration** (paste a list) | Only the characters you paste survive |')
    w('')
    w('<!-- END STATS -->')

    return '\n'.join(o)


def inject(block):
    """Replace the generated block in README.md and leave the rest alone."""
    with open(OUT, encoding='utf-8') as f:
        readme = f.read()
    i, j = readme.find(BEGIN), readme.find(END)
    if i < 0 or j < 0:
        raise SystemExit('README.md has no %s / %s markers' % (BEGIN, END))
    out = readme[:i] + block + readme[j + len(END):]
    with open(OUT, 'w', encoding='utf-8') as f:
        f.write(out)
    return len(block.split('\n'))


if __name__ == '__main__':
    n = inject(build())
    print('%s  ·  %d generated lines' % (os.path.relpath(OUT, ROOT), n))
