#!/usr/bin/env python3
"""Render SOURCES.md into sources.html.

    python3 tools/build_sources.py

SOURCES.md is the document; the page is produced from it. Keeping the two by
hand would be the same trap as a pair of coupdated READMEs: the copy nobody
opens is the one that drifts.

The Markdown subset is deliberately small, and anything outside it RAISES
instead of being dropped. A converter that silently ignores what it does not
understand turns a document into a shorter document without saying so.

2026 Alejandro Rojo Gualix - MIT
"""

import io
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, 'SOURCES.md')
OUT = os.path.join(ROOT, 'sources.html')

HEAD = '''<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Alejandro Rojo">
    <title>Chinese graphemes · sources</title>

    <link rel="stylesheet" type="text/css" href="style/common.css">
    <link rel="stylesheet" type="text/css" href="style/articulo.css">
    <link rel="stylesheet" type="text/css" href="style/theme.css">
    <link rel="stylesheet" type="text/css" href="style/article-toolbar.css">
    <script src="js/article-toolbar.js"></script>
    <!-- Generated by tools/build_sources.py from SOURCES.md. Do not edit. -->
</head>

<body data-year="2019">
    <main>
'''

FOOT = '''    </main>
</body>

</html>
'''


def esc(s):
    return s.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')


def inline(s):
    """Code spans, links, autolinks and bold. In that order: a URL inside a code
    span must not become a link, and a link label must not be escaped twice."""
    held = []

    def hold(html):
        held.append(html)
        return '\x00%d\x00' % (len(held) - 1)

    s = re.sub(r'`([^`]+)`', lambda m: hold('<code>%s</code>' % esc(m.group(1))), s)
    s = re.sub(r'\[([^\]]+)\]\(([^)\s]+)\)',
               lambda m: hold('<a href="%s">%s</a>' % (esc(m.group(2)), esc(m.group(1)))), s)
    s = re.sub(r'<((?:https?|mailto):[^>\s]+)>',
               lambda m: hold('<a href="%s">%s</a>' % (esc(m.group(1)), esc(m.group(1)))), s)
    s = esc(s)
    s = re.sub(r'\*\*([^*]+)\*\*', r'<strong>\1</strong>', s)
    s = re.sub(r'\*([^*]+)\*', r'<em>\1</em>', s)
    if '*' in s:
        raise SystemExit('unbalanced emphasis in: ' + s)
    return re.sub(r'\x00(\d+)\x00', lambda m: held[int(m.group(1))], s)


def cells(line):
    return [c.strip() for c in line.strip().strip('|').split('|')]


def render(md):
    out, i, lines = [], 0, md.split('\n')
    while i < len(lines):
        l = lines[i]
        if not l.strip():
            i += 1
            continue

        m = re.match(r'(#{1,4}) (.+)$', l)
        if m:
            n = len(m.group(1))
            out.append('<h%d>%s</h%d>' % (n, inline(m.group(2)), n))
            i += 1
            continue

        if l.startswith('> '):
            block = []
            while i < len(lines) and lines[i].startswith('>'):
                block.append(lines[i].lstrip('>').strip())
                i += 1
            out.append('<blockquote><p>%s</p></blockquote>' % inline(' '.join(block)))
            continue

        # A table: a header row, a separator row of dashes, then the body.
        if l.startswith('|') and i + 1 < len(lines) and re.match(r'^\|[\s:|-]+\|$', lines[i + 1]):
            head = cells(l)
            align = ['right' if c.endswith(':') else 'left' for c in cells(lines[i + 1])]
            i += 2
            rows = []
            while i < len(lines) and lines[i].startswith('|'):
                rows.append(cells(lines[i]))
                i += 1
            t = ['<table>', '<thead><tr>']
            for k, c in enumerate(head):
                t.append('<th style="text-align:%s">%s</th>' % (align[k], inline(c)))
            t.append('</tr></thead>')
            t.append('<tbody>')
            for r in rows:
                t.append('<tr>' + ''.join(
                    '<td style="text-align:%s">%s</td>' % (align[k] if k < len(align) else 'left',
                                                           inline(c))
                    for k, c in enumerate(r)) + '</tr>')
            t.append('</tbody></table>')
            out.append('\n'.join(t))
            continue

        if l.startswith(('- ', '* ', '1. ')):
            raise SystemExit('lists are not in the subset yet: ' + l)
        if l.startswith('|'):
            raise SystemExit('table with no separator row: ' + l)

        # A paragraph: everything up to the next blank line.
        block = []
        while i < len(lines) and lines[i].strip() and not lines[i].startswith(('#', '|', '> ')):
            block.append(lines[i].strip())
            i += 1
        out.append('<p>%s</p>' % inline(' '.join(block)))

    return '\n'.join('        ' + x.replace('\n', '\n        ') for x in out)


if __name__ == '__main__':
    md = io.open(SRC, encoding='utf-8').read()
    io.open(OUT, 'w', encoding='utf-8').write(HEAD + render(md) + '\n' + FOOT)
    print('%s  ·  %d KB' % (os.path.relpath(OUT, ROOT), os.path.getsize(OUT) // 1024))
